#
# This file is autogenerated by Laragoon for php-7.4
#

ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

RUN docker-php-ext-install pcntl
RUN docker-php-ext-install posix
COPY lagoon/php-horizon.ini /usr/local/etc/php/php.ini

CMD ["/app/scripts/start-horizon.sh"]
